### ISSUE TITLE
Create a "project" on GitHub to track your work

### ISSUE THREAD

**Issue by bnlcorp** [CrystalVulpine/VoxelPlanet#1]
- [ ] use either the basic or automated kanban template

The link to create it is: https://github.com/CrystalVulpine/VoxelPlanet/projects

Also I cannot seem to be able to put a "label" on this issue, you should investigate why because it's nice to filter or sort the issues when you have too many.

**Comment by CrystalVulpine** [comment]
I like that idea

**Comment by CrystalVulpine** [comment]
Like practically everything else though, I don't know how to use projects.

**Comment by bnlcorp** [comment]
I cannot do it for you as I don't have the rights. You must:

1. Go to https://github.com/CrystalVulpine/VoxelPlanet/projects
2. Click on the green button called "Create a project" on the upper right of the screen
3. Add a title like "VoxelPlanet Board" or something like that
4. Use the template "Basic kanban" or "Automated kanban" (both should be OK even if I haven't worked with the automated once)
5. And then move the tasks across the columns of the board to see the progress of each task

**Comment by CrystalVulpine** [comment]
Also, how the hell do you learn CMake and stuff? There are zero understandable beginner resources for it, so unless people were just born knowing how to use it (doubtful) I'm not sure how it's learned.

**Comment by bnlcorp** [comment]
CMake is not easy to learn but it's the least bad build system IMHO. You can read this for an introduction: https://cliutils.gitlab.io/modern-cmake/

The good thing is that once is it setup, you don't really need to touch it anymore (except if you want to add unit-tests or package your application and then you would have to add build steps).
