### ISSUE TITLE
Write a clang-format configuration file

### ISSUE THREAD

**Issue by bnlcorp** [CrystalVulpine/VoxelPlanet#5]
Define your own style and apply it globally (maybe automatically on every commit with git hooks, but it's not a hard requirement).

Some hints here: https://clang.llvm.org/docs/ClangFormatStyleOptions.html or https://zed0.co.uk/clang-format-configurator/ or http://clangformat.com/

**Comment by CrystalVulpine** [comment]
I use gcc, not familiar with clang.
